backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
  
media_folder: "/images"  # Media files will be stored in the repo under static/images/uploads
public_folder: "/public/images" 
  
collections:
  - name: "blog" 
    label: "Blog" 
    folder: "src/pages/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    encoding: "ascii"
    clean_accents: true
    sanitize_replacement: "_" 
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Hero Image", name: "hero", widget: "image"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}